### ISSUE TITLE
How to pronounce NDJSON?

### ISSUE THREAD

**Issue by aubergene** [ndjson/ndjson.github.io#3]
I love the spec, but **EN-DEE-JAY-sun** is a bit of a mouthful, how about **nudge-sun** as a pronounceable word-like way of naming it?

**Comment by hoegertn** [comment]
I normally use the **EN-DEE-JAY-sun** variant and I do not see any problems with it.

**Comment by aubergene** [comment]
Cool 👍  that settles it then EN-DEY-JAY-sun :)
